# Demonstração

In [66]:
import numpy as np
from sklearn.impute import SimpleImputer, KNNImputer

In [67]:
X = [[3, 4, 4], [np.nan, 6, 5], [7, 8, np.nan], [8, 8, 7]]

X

[[3, 4, 4], [nan, 6, 5], [7, 8, nan], [8, 8, 7]]

[3, 4, 3] <-
[5.5, 6, 5] <-
[1, 2, 4]
[8, 8, 7]

In [68]:
imputer = KNNImputer(n_neighbors=1)
imputer.fit_transform(X)

array([[3., 4., 4.],
       [3., 6., 5.],
       [7., 8., 7.],
       [8., 8., 7.]])

# Exercício

Realizar o Data Inputation utilizando o dataset abaixo para os seguintes casos:

- Valor arbitrário: -100.000.000
- Mediana
- Média
- End of Tail (em +3sigma)
- KNN Inputer

**Dica**: Cuidado para não utilizar o mesmo dataset nos diferentes exercícios

In [69]:
# knn imputation transform for the horse colic dataset
from numpy import isnan
import pandas as pd

# Carrega  dataset
url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/horse-colic.csv'
df = pd.read_csv(url, header=None, na_values='?')

df

,0,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,26,27
0,2.0,1,530101,38.5,66.0,28.0,3.0,3.0,NaN,2.0,...,45.0,8.4,NaN,NaN,2.0,2,11300,0,0,2
1,1.0,1,534817,39.2,88.0,20.0,NaN,NaN,4.0,1.0,...,50.0,85.0,2.0,2.0,3.0,2,2208,0,0,2
2,2.0,1,530334,38.3,40.0,24.0,1.0,1.0,3.0,1.0,...,33.0,6.7,NaN,NaN,1.0,2,0,0,0,1
3,1.0,9,5290409,39.1,164.0,84.0,4.0,1.0,6.0,2.0,...,48.0,7.2,3.0,5.3,2.0,1,2208,0,0,1
4,2.0,1,530255,37.3,104.0,35.0,NaN,NaN,6.0,2.0,...,74.0,7.4,NaN,NaN,2.0,2,4300,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,1.0,1,533886,NaN,120.0,70.0,4.0,NaN,4.0,2.0,...,55.0,65.0,NaN,NaN,3.0,2,3205,0,0,2
296,2.0,1,527702,37.2,72.0,24.0,3.0,2.0,4.0,2.0,...,44.0,NaN,3.0,3.3,3.0,1,2208,0,0,1
297,1.0,1,529386,37.5,72.0,30.0,4.0,3.0,4.0,1.0,...,60.0,6.8,NaN,NaN,2.0,1,3205,0,0,2
298,1.0,1,530612,36.5,100.0,24.0,3.0,3.0,3.0,1.0,...,50.0,6.0,3.0,3.4,1.0,1,2208,0,0,1
299,1.0,1,534618,37.2,40.0,20.0,NaN,NaN,NaN,NaN,...,36.0,62.0,1.0,1.0,3.0,2,6112,0,0,2

In [70]:
#Ajuste Para separar a coluna target

target_column = 23
y = df[target_column]
x_columns = df.columns.to_list()
x_columns.remove(target_column)
X = df[x_columns]

In [71]:
#Total missing
X.isnull().sum()

0       1
1       0
2       0
3      60
4      24
5      58
6      56
7      69
8      47
9      32
10     55
11     44
12     56
13    104
14    106
15    247
16    102
17    118
18     29
19     33
20    165
21    198
22      1
24      0
25      0
26      0
27      0
dtype: int64

## Respostas abaixo:

In [72]:
X

,0,1,2,3,4,5,6,7,8,9,...,17,18,19,20,21,22,24,25,26,27
0,2.0,1,530101,38.5,66.0,28.0,3.0,3.0,NaN,2.0,...,5.0,45.0,8.4,NaN,NaN,2.0,11300,0,0,2
1,1.0,1,534817,39.2,88.0,20.0,NaN,NaN,4.0,1.0,...,2.0,50.0,85.0,2.0,2.0,3.0,2208,0,0,2
2,2.0,1,530334,38.3,40.0,24.0,1.0,1.0,3.0,1.0,...,1.0,33.0,6.7,NaN,NaN,1.0,0,0,0,1
3,1.0,9,5290409,39.1,164.0,84.0,4.0,1.0,6.0,2.0,...,NaN,48.0,7.2,3.0,5.3,2.0,2208,0,0,1
4,2.0,1,530255,37.3,104.0,35.0,NaN,NaN,6.0,2.0,...,NaN,74.0,7.4,NaN,NaN,2.0,4300,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,1.0,1,533886,NaN,120.0,70.0,4.0,NaN,4.0,2.0,...,5.0,55.0,65.0,NaN,NaN,3.0,3205,0,0,2
296,2.0,1,527702,37.2,72.0,24.0,3.0,2.0,4.0,2.0,...,4.0,44.0,NaN,3.0,3.3,3.0,2208,0,0,1
297,1.0,1,529386,37.5,72.0,30.0,4.0,3.0,4.0,1.0,...,5.0,60.0,6.8,NaN,NaN,2.0,3205,0,0,2
298,1.0,1,530612,36.5,100.0,24.0,3.0,3.0,3.0,1.0,...,4.0,50.0,6.0,3.0,3.4,1.0,2208,0,0,1
299,1.0,1,534618,37.2,40.0,20.0,NaN,NaN,NaN,NaN,...,1.0,36.0,62.0,1.0,1.0,3.0,6112,0,0,2

In [73]:
arbitrary_imputer = SimpleImputer(strategy='constant', fill_value=-100_000_000)
X_arbitrary = pd.DataFrame(arbitrary_imputer.fit_transform(X), columns=X.columns)

X_arbitrary

,0,1,2,3,4,5,6,7,8,9,...,17,18,19,20,21,22,24,25,26,27
0,2.0,1.0,530101.0,38.5,66.0,28.0,3.0,3.0,-100000000.0,2.0,...,5.0,45.0,8.4,-100000000.0,-100000000.0,2.0,11300.0,0.0,0.0,2.0
1,1.0,1.0,534817.0,39.2,88.0,20.0,-100000000.0,-100000000.0,4.0,1.0,...,2.0,50.0,85.0,2.0,2.0,3.0,2208.0,0.0,0.0,2.0
2,2.0,1.0,530334.0,38.3,40.0,24.0,1.0,1.0,3.0,1.0,...,1.0,33.0,6.7,-100000000.0,-100000000.0,1.0,0.0,0.0,0.0,1.0
3,1.0,9.0,5290409.0,39.1,164.0,84.0,4.0,1.0,6.0,2.0,...,-100000000.0,48.0,7.2,3.0,5.3,2.0,2208.0,0.0,0.0,1.0
4,2.0,1.0,530255.0,37.3,104.0,35.0,-100000000.0,-100000000.0,6.0,2.0,...,-100000000.0,74.0,7.4,-100000000.0,-100000000.0,2.0,4300.0,0.0,0.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,1.0,1.0,533886.0,-100000000.0,120.0,70.0,4.0,-100000000.0,4.0,2.0,...,5.0,55.0,65.0,-100000000.0,-100000000.0,3.0,3205.0,0.0,0.0,2.0
296,2.0,1.0,527702.0,37.2,72.0,24.0,3.0,2.0,4.0,2.0,...,4.0,44.0,-100000000.0,3.0,3.3,3.0,2208.0,0.0,0.0,1.0
297,1.0,1.0,529386.0,37.5,72.0,30.0,4.0,3.0,4.0,1.0,...,5.0,60.0,6.8,-100000000.0,-100000000.0,2.0,3205.0,0.0,0.0,2.0
298,1.0,1.0,530612.0,36.5,100.0,24.0,3.0,3.0,3.0,1.0,...,4.0,50.0,6.0,3.0,3.4,1.0,2208.0,0.0,0.0,1.0
299,1.0,1.0,534618.0,37.2,40.0,20.0,-100000000.0,-100000000.0,-100000000.0,-100000000.0,...,1.0,36.0,62.0,1.0,1.0,3.0,6112.0,0.0,0.0,2.0

In [74]:
median_imputer = SimpleImputer(strategy='median')
X_median = pd.DataFrame(median_imputer.fit_transform(X), columns=X.columns)

X_median

,0,1,2,3,4,5,6,7,8,9,...,17,18,19,20,21,22,24,25,26,27
0,2.0,1.0,530101.0,38.5,66.0,28.0,3.0,3.0,3.0,2.0,...,5.0,45.0,8.4,2.0,2.25,2.0,11300.0,0.0,0.0,2.0
1,1.0,1.0,534817.0,39.2,88.0,20.0,3.0,2.0,4.0,1.0,...,2.0,50.0,85.0,2.0,2.00,3.0,2208.0,0.0,0.0,2.0
2,2.0,1.0,530334.0,38.3,40.0,24.0,1.0,1.0,3.0,1.0,...,1.0,33.0,6.7,2.0,2.25,1.0,0.0,0.0,0.0,1.0
3,1.0,9.0,5290409.0,39.1,164.0,84.0,4.0,1.0,6.0,2.0,...,4.0,48.0,7.2,3.0,5.30,2.0,2208.0,0.0,0.0,1.0
4,2.0,1.0,530255.0,37.3,104.0,35.0,3.0,2.0,6.0,2.0,...,4.0,74.0,7.4,2.0,2.25,2.0,4300.0,0.0,0.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,1.0,1.0,533886.0,38.2,120.0,70.0,4.0,2.0,4.0,2.0,...,5.0,55.0,65.0,2.0,2.25,3.0,3205.0,0.0,0.0,2.0
296,2.0,1.0,527702.0,37.2,72.0,24.0,3.0,2.0,4.0,2.0,...,4.0,44.0,7.5,3.0,3.30,3.0,2208.0,0.0,0.0,1.0
297,1.0,1.0,529386.0,37.5,72.0,30.0,4.0,3.0,4.0,1.0,...,5.0,60.0,6.8,2.0,2.25,2.0,3205.0,0.0,0.0,2.0
298,1.0,1.0,530612.0,36.5,100.0,24.0,3.0,3.0,3.0,1.0,...,4.0,50.0,6.0,3.0,3.40,1.0,2208.0,0.0,0.0,1.0
299,1.0,1.0,534618.0,37.2,40.0,20.0,3.0,2.0,3.0,1.0,...,1.0,36.0,62.0,1.0,1.00,3.0,6112.0,0.0,0.0,2.0

In [75]:
mean_imputer = SimpleImputer(strategy='mean')
X_mean = pd.DataFrame(mean_imputer.fit_transform(X), columns=X.columns)

X_mean

,0,1,2,3,4,5,6,7,8,9,...,17,18,19,20,21,22,24,25,26,27
0,2.0,1.0,530101.0,38.500000,66.0,28.0,3.000000,3.000000,2.853755,2.00000,...,5.000000,45.0,8.400000,2.037037,3.019608,2.0,11300.0,0.0,0.0,2.0
1,1.0,1.0,534817.0,39.200000,88.0,20.0,2.348361,2.017316,4.000000,1.00000,...,2.000000,50.0,85.000000,2.000000,2.000000,3.0,2208.0,0.0,0.0,2.0
2,2.0,1.0,530334.0,38.300000,40.0,24.0,1.000000,1.000000,3.000000,1.00000,...,1.000000,33.0,6.700000,2.037037,3.019608,1.0,0.0,0.0,0.0,1.0
3,1.0,9.0,5290409.0,39.100000,164.0,84.0,4.000000,1.000000,6.000000,2.00000,...,3.692308,48.0,7.200000,3.000000,5.300000,2.0,2208.0,0.0,0.0,1.0
4,2.0,1.0,530255.0,37.300000,104.0,35.0,2.348361,2.017316,6.000000,2.00000,...,3.692308,74.0,7.400000,2.037037,3.019608,2.0,4300.0,0.0,0.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,1.0,1.0,533886.0,38.167917,120.0,70.0,4.000000,2.017316,4.000000,2.00000,...,5.000000,55.0,65.000000,2.037037,3.019608,3.0,3205.0,0.0,0.0,2.0
296,2.0,1.0,527702.0,37.200000,72.0,24.0,3.000000,2.000000,4.000000,2.00000,...,4.000000,44.0,24.456929,3.000000,3.300000,3.0,2208.0,0.0,0.0,1.0
297,1.0,1.0,529386.0,37.500000,72.0,30.0,4.000000,3.000000,4.000000,1.00000,...,5.000000,60.0,6.800000,2.037037,3.019608,2.0,3205.0,0.0,0.0,2.0
298,1.0,1.0,530612.0,36.500000,100.0,24.0,3.000000,3.000000,3.000000,1.00000,...,4.000000,50.0,6.000000,3.000000,3.400000,1.0,2208.0,0.0,0.0,1.0
299,1.0,1.0,534618.0,37.200000,40.0,20.0,2.348361,2.017316,2.853755,1.30597,...,1.000000,36.0,62.000000,1.000000,1.000000,3.0,6112.0,0.0,0.0,2.0

In [76]:
def end_of_tail_impute(df):
    df_imputed = df.copy()
    for col in df.columns:
        mean = df[col].mean()
        std = df[col].std()
        end_tail_value = mean + 3 * std
        df_imputed[col].fillna(end_tail_value, inplace=True)
    return df_imputed

In [77]:
X_end_tail = end_of_tail_impute(X)

X_end_tail

<ipython-input-76-36954a0851e0>:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_imputed[col].fillna(end_tail_value, inplace=True)

,0,1,2,3,4,5,6,7,8,9,...,17,18,19,20,21,22,24,25,26,27
0,2.0,1,530101,38.500000,66.0,28.0,3.000000,3.000000,7.714637,2.000000,...,5.000000,45.0,8.400000,4.451751,8.925308,2.0,11300,0,0,2
1,1.0,1,534817,39.200000,88.0,20.0,5.483522,5.144599,4.000000,1.000000,...,2.000000,50.0,85.000000,2.000000,2.000000,3.0,2208,0,0,2
2,2.0,1,530334,38.300000,40.0,24.0,1.000000,1.000000,3.000000,1.000000,...,1.000000,33.0,6.700000,4.451751,8.925308,1.0,0,0,0,1
3,1.0,9,5290409,39.100000,164.0,84.0,4.000000,1.000000,6.000000,2.000000,...,8.167484,48.0,7.200000,3.000000,5.300000,2.0,2208,0,0,1
4,2.0,1,530255,37.300000,104.0,35.0,5.483522,5.144599,6.000000,2.000000,...,8.167484,74.0,7.400000,4.451751,8.925308,2.0,4300,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,1.0,1,533886,40.364783,120.0,70.0,4.000000,5.144599,4.000000,2.000000,...,5.000000,55.0,65.000000,4.451751,8.925308,3.0,3205,0,0,2
296,2.0,1,527702,37.200000,72.0,24.0,3.000000,2.000000,4.000000,2.000000,...,4.000000,44.0,106.881957,3.000000,3.300000,3.0,2208,0,0,1
297,1.0,1,529386,37.500000,72.0,30.0,4.000000,3.000000,4.000000,1.000000,...,5.000000,60.0,6.800000,4.451751,8.925308,2.0,3205,0,0,2
298,1.0,1,530612,36.500000,100.0,24.0,3.000000,3.000000,3.000000,1.000000,...,4.000000,50.0,6.000000,3.000000,3.400000,1.0,2208,0,0,1
299,1.0,1,534618,37.200000,40.0,20.0,5.483522,5.144599,7.714637,2.738856,...,1.000000,36.0,62.000000,1.000000,1.000000,3.0,6112,0,0,2

In [78]:
knn_imputer = KNNImputer(n_neighbors=2)
X_knn = pd.DataFrame(knn_imputer.fit_transform(X), columns=X.columns)

X_knn

,0,1,2,3,4,5,6,7,8,9,...,17,18,19,20,21,22,24,25,26,27
0,2.0,1.0,530101.0,38.50,66.0,28.0,3.0,3.0,2.0,2.0,...,5.0,45.0,8.4,3.0,4.25,2.0,11300.0,0.0,0.0,2.0
1,1.0,1.0,534817.0,39.20,88.0,20.0,2.0,1.0,4.0,1.0,...,2.0,50.0,85.0,2.0,2.00,3.0,2208.0,0.0,0.0,2.0
2,2.0,1.0,530334.0,38.30,40.0,24.0,1.0,1.0,3.0,1.0,...,1.0,33.0,6.7,2.5,4.80,1.0,0.0,0.0,0.0,1.0
3,1.0,9.0,5290409.0,39.10,164.0,84.0,4.0,1.0,6.0,2.0,...,4.5,48.0,7.2,3.0,5.30,2.0,2208.0,0.0,0.0,1.0
4,2.0,1.0,530255.0,37.30,104.0,35.0,3.0,3.0,6.0,2.0,...,3.0,74.0,7.4,2.0,3.35,2.0,4300.0,0.0,0.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,1.0,1.0,533886.0,38.25,120.0,70.0,4.0,3.0,4.0,2.0,...,5.0,55.0,65.0,1.5,2.00,3.0,3205.0,0.0,0.0,2.0
296,2.0,1.0,527702.0,37.20,72.0,24.0,3.0,2.0,4.0,2.0,...,4.0,44.0,7.4,3.0,3.30,3.0,2208.0,0.0,0.0,1.0
297,1.0,1.0,529386.0,37.50,72.0,30.0,4.0,3.0,4.0,1.0,...,5.0,60.0,6.8,2.0,3.75,2.0,3205.0,0.0,0.0,2.0
298,1.0,1.0,530612.0,36.50,100.0,24.0,3.0,3.0,3.0,1.0,...,4.0,50.0,6.0,3.0,3.40,1.0,2208.0,0.0,0.0,1.0
299,1.0,1.0,534618.0,37.20,40.0,20.0,1.0,2.0,3.0,1.0,...,1.0,36.0,62.0,1.0,1.00,3.0,6112.0,0.0,0.0,2.0